### ISSUE TITLE
SEO problems

### ISSUE THREAD

**Issue by stewmorg** [bullhorn/career-portal#107]
Hi there, I'm having problems getting any of the content displayed/rendered by the Open Source Career portal to be indexed by Google or be recognised by Google as a separate page.  Is this a known issue for the career portal?

**Comment by krsween** [comment]
Hey, stewmorg—

From an architectural standpoint, OSCP is a web app which makes it difficult to integrate it with SEO, but not at all impossible. In fact some, SEO indexing does take place on the app, but in order for Google (and other search engines) to index the app more thoroughly there is more work required. There are several really thorough articles on how to make this integration. I really like the one by [Deep Crawl](https://www.deepcrawl.com/blog/best-practice/angular-js-and-seo/) but there a tons of others. Since it's a challenging initiative and it can carry implementation challenges for our users ([HTML5 Routing](http://ericclemmons.com/angular/using-html5-not-hash-routes/) would require server configuration changes for some users), we had to consider whether or not this took precedence over other initiatives (i.e. uploading resumes via mobile devices or LinkedIn integrations).

From a strategy perspective, we asked ourselves whether or not SEO support would be of large benefit to our users and their candidates. From most of the data we've seen, it was more beneficial to extend our larger platform to include extensions for Indeed, Monster, LinkedIn and other job hunting APIs because most applicants searching for opportunities leverage those site first, and rarely go outside of them. Another deciding factor was the longevity of our users' job postings. How long would it take for Google to index a job? And, would that indexing occur before a position had already been filled? Likely our users' would be filling positions before Google would even have them. So, for the majority of our users' candidates it didn't seem like they would realize significant value.

Based on these factors (and several others), SEO didn't seem as important as other features in this application. But, with the article above, if you believe that this is an important feature for your version of OSCP, you can extend our app to embody this functionality. Also, to help support this extension, if you push your modifications to OSCP to Github feel free to send questions to me (@krsween) with questions as they arise.

**Comment by stewmorg** [comment]
Thanks for krsween.  The HTML5 routing strategy isn't too tricky to implement, we've already done a POC for this and it works pretty well. I'll keep you posted on push a branch when/if I find time.

**Comment by krsween** [comment]
@stewmorg — Please do! I'd love to contribute if I can.
