### ISSUE TITLE
HTML parser for list is missing whitespace between a few words.

### ISSUE THREAD

**Issue by jasonNpMktg** [bullhorn/career-portal#140]
Hi,
I'm having an issue where sometimes the text that is parsed from a job posting onto the list is missing some whitespace. When looking at the detailed view of the page, this issue disappears. 
I've customized this portal - but I've only really changed the CSS and the layout - haven't touched any of the models or controllers. You can see it live here:
http://fishrecruit.com/job-postings.php#/jobs

This issue is very hard to spot - but here are some screenshots.

List/grid view
![image](https://user-images.githubusercontent.com/29716303/27559431-8d3e02c4-5a8e-11e7-9491-ee163f3d1075.png)

Detailed View
![image](https://user-images.githubusercontent.com/29716303/27559452-a6365966-5a8e-11e7-9190-2dd0288f1729.png)

I'm fairly certain this is not CSS. Using the element inspector, I'm able to see that the text itself has been outputted in this way. 
![image](https://user-images.githubusercontent.com/29716303/27559582-052d208a-5a8f-11e7-8c61-f04f4b8095f9.png)

The bewildering thing is that this only happens with certain job postings, and most of the others are perfectly fine. 

Thanks in advanced.

**Comment by bulbajackel** [comment]
Heya, this is possible this is due to the HTML in the job posting utilizing `&NBSP` instead of a normal whitespace space within Bullhorn itself.  This can be seen by pressing the source button within Bullhorn.  

Currently, you can see the change required in the [pull request seen here](https://github.com/bullhorn/career-portal/pull/133) that details the code change necessary to display the nbsp character appropriately.   

I would suggest applying the changes to the file in `src/app/filters/striphtml.filter.js` so that you are able to successfully utilize the special characters in the preview.

**Comment by bvkimball** [comment]
fixed by #133
