### ISSUE TITLE
Connectivity with Google Job Search

### ISSUE THREAD

**Issue by talent1** [bullhorn/career-portal#143]
This isn't an issue as much as a question, but has anyone found a solution to connecting the WordPress Plugin to Google Jobs (adding job listing structured data to the webpage)? I contacted Bullhorn and they said that it would be a WordPress question as they have nothing to do with it. 

https://developers.google.com/search/docs/data-types/job-postings 

Thanks!

**Comment by bulbajackel** [comment]
To begin, you will want to ensure, your portal is has the ability to be indexed on Google.  I suggest checking out the [post here](https://github.com/bullhorn/career-portal/issues/107#issuecomment-269329104) that details utilizing HTML5 routing so Google will be able to find your individual jobs.  

Once that has been accomplished you should be able to add the structured data attributes to the HTML of your Jobs.  I suggest checking out [Google's tool](https://search.google.com/structured-data/testing-tool/) for this. 

Please let me know if you have any questions.

**Comment by talent1** [comment]
Is there a way to do this when each job doesn't have it's own link? Since we use the portal all of our jobs sit on the same page and the only way to get a unique link is when you hit share and a link comes up in an email. Thanks!

**Comment by bvkimball** [comment]
So, the career portal today is a SPA (single page application) and is not configured to work this way out of the box.  To support this you will need to adjust the AngularJS location provider to use HTML5 routing, [here](https://ngmilk.rocks/2015/03/09/angularjs-html5-mode-or-pretty-urls-on-apache-using-htaccess/) is a helpful article.

This won't solve all of your SEO problems because angular doesn't render anything to the page immediately. Supposedly Google has added optimization to be able to crawl these types of pages when the page is rendered (but no promises on how that works).  If that did work you would have to publish a site-map.xml to Google as described in the developer docs.  Then once google hit the page you would need to have the page render Google’s Structured Data in the appropriate places.

So features needs:

- [ ] HTML5 routing mode
- [ ] Rendering script tag with Google's Structured Data to page
- [ ] Auto generate and Publishing of sitemap.xml to Google

All of these features are significant in scope. It has been identified to be added in a future iteration of the Career Portal, but until then you can try to implement these yourself.

We will use this ticket to track any progress we make in this.

**Comment by pbearne** [comment]
If SEO is important to you [Matador Jobs WordPress plugin](https://matadorjobs.com) adds Google Jobs JSON data as well all the standard SEO via WordPress SEO Plugins

**Comment by bscottroberts** [comment]
Any movement on this? We don't have a WordPress website but would like for our Bullhorn Career Portal Jobs to show up for Google Jobs.

**Comment by Valenz1** [comment]
We too have our jobs published on the Bullhorn Career Portal and would like to know the best way to get our jobs indexed by Google for jobs.

**Comment by bscottroberts** [comment]
Any movement on this? We would like for our jobs to show up in Google Jobs.

**Comment by charlesabarnes** [comment]
This is something that we are working on currently. This feature will be available in version3.0 of the career portal that we hope to have in a `pre-release` status in the coming weeks. 

However, for the feature to work, it would require a different hosting solution than whats usually used currently as the solution was to implement server side indexing.   

Let me know if you have any more questions
