### ISSUE TITLE
Cannot Search Keyword with # character

### ISSUE THREAD

**Issue by Fyrearm** [bullhorn/career-portal#178]
https://github.com/bullhorn/career-portal/blob/cec4a679f63fad6a837480b33752a71c07f90928/src/app/services/search.service.js#L173

Consider adding: 
`query = encodeURIComponent(query);`

Also is there a way to search a keyword with a period.  For example .NET or ASP.NET?  I'm not able to get this to work at all, possibly something on the BullHorn side prevent this?

**Comment by bulbajackel** [comment]
If you already have the fix in place, feel free to submit a pull request to correct the `#` issue, otherwise we will investigate the change and implement it ASAP.

For the .NET search I am investigating here on my end and I will let you what I find.  

Please let me know if you have any more questions.

**Comment by ckapp-bullhorn** [comment]
No, sorry.  These are analyzed strings.  The period is punctuation and treated as a word break. "ASP.NET" will be indexed as "ASP" and "NET".
