### ISSUE TITLE
Adjust minimum file size to 15KB

### ISSUE THREAD

**Issue by ahuberbullhorn** [bullhorn/career-portal#18]
Currently, the minimum file size a candidate can attach as a resume is 30KB. We should drop this to 15KB.

![image](https://cloud.githubusercontent.com/assets/13653329/11035495/7aa4f1dc-86b8-11e5-8316-d42018fc4182.png)

**Comment by TheReal** [comment]
@ahuberbullhorn This is already configurable (per CP instance) via app.json, under the "minUploadSize" key. Pre-populated value is 30720 (bytes), which is the effective default for any new CP installation. We could very easily change the pre-populated (default) value to 15KB by modifying the app.json.template file in source and shipping with the next release.

The REX parsing service requires that text input be of a certain minimum length or it will fail. This may or may not be under 15K. @ahuberbullhorn can you get a definitive answer on minimum input size from tech ops? We'll then change the pre-populated value to a safe default.

**Comment by muchemwa** [comment]
Have you been able to confirm that changing the minimum upload size to 15 won't cause errors in parsing?

**Comment by TheReal** [comment]
@muchemwa Thanks for your comment. The current version of Bullhorn Career Portal does not make a minimum file size check prior to upload even though that configuration value continues to persist in app.json. It is simply not consulted anymore. Your candidates should be able to upload files as small as 4 KB without issue.

We've taken a look at the code and realized we should both update the default value to 4096 (4 KB) and reinstate the minimum file size check for uploaded resumes. Since the Apply with LinkedIn flow involves the code consuming a LinkedIn profile to craft a parsable resume, we have to make this feature compatible with this check; likely by ignoring the configured minimum and guaranteeing that the crafted resume meets the parsing infrastructure minimum (about 1 KB) of the Bullhorn back-end.

**Comment by krsween** [comment]
Minimum file size has been lowered to 4kb.
