### ISSUE TITLE
New Build - No Results

### ISSUE THREAD

**Issue by jontheophilus** [bullhorn/career-portal#21]
I did a clone of the repo, then a build and run via:

gulp --corp='xxxxx' --sl='SL1' --companyName='xxxxx xxxxx'
gulp serve --corp='xxxxx' --sl='SL1' --companyName='xxxxx xxxxx'

The portal loads, but when I search for something nothing happens, no error messages.

To confirm: the corpToken is the 5 digit code after the REST URL:

Our staging system REST URL:
https://rest9.bullhornstaffing.com/rest-services/xxxxx/

**Comment by TheReal** [comment]
@jontheophilus The corpToken is indeed the path step succeeding the rest-services context root in your BH REST URL. Try running the gulp commands with an --sl argument value that does not include the 'SL' prefix. In your example, the argument would read --sl='1'. Note that your staging system URL correctly implies SL9, as denoted by the digits 'restXX' in the URL hostname, so wiring the portal to your staging system/data would imply an argument of --sl='9'.

All production swimlane values are integers and we would have preferred to type the --SL argument as such, along with the backing value in app.json; however the downlevel environments internal to Bullhorn are not necessarily integers and we needed to support them in our development and CI systems. Thus a string-typed argument amd JSON config value... which can be confusing for app writers.

Also note that you need only run the gulp serve command to launch a local build of the portal; this command compiles/builds the package prior to serving it out of node express.

Let us know if the revised argument works for you.

**Comment by jgodi** [comment]
@TheReal Maybe we should do some checking on the arguments and possibly provide some better insight or chop off pieces that aren't needed.

**Comment by TheReal** [comment]
@jgodi It would be trivial to parse an int out of the argument string, given a set of static character prefixes. This would be compatible with development and CI system naming conventions internal to Bullhorn. New issue?

**Comment by jgodi** [comment]
Ya, I would say and then just reference this task on it. We can keep this open until @jontheophilus is up and running.

**Comment by jontheophilus** [comment]
I tried with both our production and staging systems. No luck. Is there a way to turn on verbose logging?

Side note: How is the portal able to authenticate with just the corpToken? Our current website uses the REST API and we maintain the access/refresh tokens.

**Comment by TheReal** [comment]
Ah yes. Have you contacted Bullhorn support to activate Career Portal / Public API access? This is a required step in order to get data feeding to your portal. More details are in the GitHub wiki article.

The reason for this has to do with your side note. Bullhorn has exposed a small subset of the BH REST API to public/anonymous consumers. All the endpoint needs to know is which Bullhorn client (via the corpToken and swimlane) the consumer, in this case the Career Portal, is attempting to call API members on. This is equivalent to how the classic portal, now deprecated, exposes data to anonymous users.

No session management is required. However, to publicly expose the necessary data, we require that the Bullhorn client intentionally open up this API subset via request and support-managed configuration.

Apologies that this is not super clear in documentation yet. We are currently in a limited private beta, and expect that most of our clients will not bother with the source code, opting instead for the compiled package out of the box. Whether a portal consumer chooses the package or source code route, the public API configuration requirement is the same.

All of us at Bullhorn are excited to engage our clients and the wider development community by making career portal source code available for feedback, extension and outright code forks.

Let us know if your issue is resolved after support gets you configured!

**Comment by jontheophilus** [comment]
@TheReal - I did contact support to get the REST credentials for the new portal (in staging), but I don't think they were aware of the public API feature. I will make that request today.

**Comment by TheReal** [comment]
Thanks @jontheophilus . I've got a line out to the Career Portal SME in our support organization, who has a team of Public API-aware customer care representatives. We'll get you fixed up.

**Comment by jontheophilus** [comment]
@TheReal - Support was able to enable that setting for me and we're up and running.

Quick Note: your docs list the flag as --corpToken=, when it seems to just be --corp=

Thanks for the help. We're interested in seeing where this project goes and how we could incorporate it on our website. Nice work so far!

**Comment by TheReal** [comment]
Thanks @jontheophilus !

@jgodi, can you verify the gulp build scripts take both "corpToken" and "corp" as a app.json.template expand argument? The realized app.json file used "corpToken" as its key, but supporting both would be ideal.

**Comment by jgodi** [comment]
Command line arguments updated! Good catch @jontheophilus! Glad you were able to get up and running.

**Comment by jontheophilus** [comment]
Thanks. Can confirm it’s working with corpToken now.
