### ISSUE TITLE
Duplicate Categories displaying issue

### ISSUE THREAD

**Issue by sarmstronghxm** [bullhorn/career-portal#253]
The problem is that we have duplicate Categories displaying on our Open Source Career Portal (OSCP) – see below.  This is due to having recruiters on each of our private labels publishing jobs from the same category (which they have to do.)  What we want is to have these categories collapse into one (show only once) with the total jobs from both private labels shown (i.e., Customer Service……7; Sales…..9).  Is this possible with the Open Source Career Portal?  

Here is an image of what's happening: https://www.evernote.com/l/AEgXlCME1l1KDLkaBnvJToVTWZSyT_qqos0

**Comment by charlesabarnes** [comment]
They are shown as separate categories because the portal displays them by category ID and not by label.   It is possible, but this would require code intervention in your portal.    What you can do is do some front end data manipulation to have an array of objects with label and values (which would be the Ids), then once a category is selected, you can do a request for all 3 categories at once.

The object would look something similar to the example in this [stack overflow thread](https://stackoverflow.com/questions/33850412/merge-javascript-objects-in-array-with-same-key).   

Please let me know if you have any more questions.

**Comment by sarmstronghxm** [comment]
I haven't seen anywhere in the application that I can add any code though.  Can you point me to where I'd go there.  The client side is all angular so I'm not sure there is much I can do on the client side.

**Comment by charlesabarnes** [comment]
The change would need to be done in the client side angular for the portal.  You would be able to get started by cloning this repository

**Comment by sarmstronghxm** [comment]
Oh duh.  Sorry, I thought this was the same code that's on the clients site.  Got it.  Thank you.

**Comment by sarmstronghxm** [comment]
Where would I find the clients Corp Token and Swimlane for building this?

**Comment by charlesabarnes** [comment]
It's in the app.json file of their career portal. This is publicly accessible.  It would be at domain.com/careers/app.json
