### ISSUE TITLE
Text wrap during mobile viewing

### ISSUE THREAD

**Issue by davidjarboe** [bullhorn/career-portal#28]
My job descriptions are not text wrapped when viewing from Chrome mobile browser.  Instead words are being chopped into 2 and letters are left by themselves.
Is this a coding change that I need to make or is it something on the BullHorn side?

**Comment by TheReal** [comment]
Thanks for reaching out @davidjarboe . We attempted repro in Chrome for Windows, simulating various mobile browsers, to no avail. Can you:

1. Document specific repro steps, perhaps including a screenshot? We want to make sure we are looking in the same place
2. Document the device spec and browser version for your repro?
3. If deployed, send us the URL of the page exhibiting this issue?

**Comment by davidjarboe** [comment]
I attached a screen shot from my phone.
The Web address is verticalrecruiting.com/careers
I only have 1 job feeding into the portal currently so you should find it
easily.
The mobile chrome version I use is 47.0.2526.83.  In on a Samsung Galaxy S6.

**Comment by krsween** [comment]
Hey, @davidjarboe—I've checked into this and I was able to reproduce this on my machine. 

It looks like the Job Description data that's getting passed in is wrapped in `<pre>` tags. Is that an intentional formatting (e.g. `<pre>\r\nEstablished practice`)? If that description is wrapped in `<pre>` tags all of the Career Portal typography applied to the description field will be ignored.

Also, when looking at your configuration I noticed that the LinkedIn Client ID for your app is a URL (https://www.linkedin.com/in/david-jarboe-7604ba16). Make sure that you pull in the client ID from the developer portal of LinkedIn. You can get that here: https://developer.linkedin.com/

**Comment by SF4H** [comment]
Hi @krsween - I'm having the same issue with <pre> tags surrounding my job description. Can you tell me how to remove/change them? Here's my career portal: http://customsalesteam4hire.com/#/jobs. 

Thank you!

**Comment by davidjarboe** [comment]
For some reason BullHorn is defaulting into a "formatted" body in the job description page.  The text "pre" shows at the bottom of the editing box.  When you begin to create your job keep an eye on it.  Type up the job ad how you'd like to see it, then select all the text and make sure the second drop down tab is "Normal (DIV)" mode.  Not formatted (pre) mode!  That fixed it for me.

**Comment by krsween** [comment]
Hey @SF4H—Was @davidjarboe's suggestion helpful? If not, let me know and I'd be glad to escalate this to our Customer Support team so that they can provide more direction.

**Comment by SF4H** [comment]
@krsween Yes! I just tested it and @davidjarboe 's suggestion worked perfectly - thanks!

**Comment by krsween** [comment]
Awesome! Thanks for the help @davidjarboe!
