### ISSUE TITLE
Attachment file size limit 

### ISSUE THREAD

**Issue by mukoy** [bullhorn/career-portal#318]
Hi,

What's the file size limit of the attachment and how do we configure it?
Thanks.

**Comment by charlesabarnes** [comment]
Hello,
The feature to define the max/min upload size of the resume was removed in Version v3.  I can use this as a feature request to add the functionality back in.  However, if you would like to modify the code for this, you  can add a property of `layoutOptions: {customValidation: {action: 'upload', fn: your_custom_validation_function() }}` to the resume control.  

Please let me know if you have any more questions

https://github.com/bullhorn/career-portal/blob/master/src/app/job-list/job-details/apply-modal/apply-modal.component.ts#L153-L157

**Comment by mukoy** [comment]
Hi @charlesabarnes, just need to know the filesize limit as of the moment, is it 2mb? thanks.

**Comment by charlesabarnes** [comment]
There is currently not a file size limit that I am aware of.  Definitely more than 5MB.

**Comment by mukoy** [comment]
Hi @charlesabarnes , we did multiple test with multiple users and we're getting a 2mb limit, how do we increase this? Thanks.

**Comment by charlesabarnes** [comment]
You're right, there's an error that occurs on files greater than 2MB,  I have tested it out in a few of my environments.  

 As this is an error in the public API itself and not the Angular Career Portal project, I suggest [contacting Bullhorn Support](https://www.bullhorn.com/technical-support/) as this will allow the issue to be properly tracked and for you to be notified when the fix is released. 

Please let me know if you have any more questions.

**Comment by pbearne** [comment]
If you are using WP look at[ matador jobs ](https://matadorjobs.com/)as we use the private API we don't have the same limit
