### ISSUE TITLE
OSCP is down again 

### ISSUE THREAD

**Issue by shokyk** [bullhorn/career-portal#347]
INSERT SHORT DESCRIPTION EXPLAINING THE HIGH-LEVEL REASON FOR THE NEW ISSUE HERE.

## Current behavior

-An error has occurred while loading. Please refresh the page and try again.

## Expected behavior
show job board
-

## Steps to replicate behavior

1. https://apcareers.us/

## Screenshots

__Current__

__Expected__

**Comment by charlesabarnes** [comment]
Hello,  Please contact Bullhorn support for more immediate assistance with this issue.   I appreciate the heads up however and will be reaching out internally about this.

**Comment by shokyk** [comment]
Yeah – their only advice was to post to you – but it just came back up… this happens a lot!

**Comment by shokyk** [comment]
Is there a way to make the facebook and other shares to actually share the one job a person is currently viewing instead of just share a link to the whole board?

**Comment by inflightcrewconnections** [comment]
I am still getting this error, any idea why?
https://www.inflightcrewconnections.com/work-for-us/

**Comment by charlesabarnes** [comment]
It appears as if this is due to the following setting being empty in the Wordpress plugin 

![image](https://user-images.githubusercontent.com/4327754/89931608-06af7a80-dbd2-11ea-9e03-a29a56f88110.png)

The text you want in the field is `id,title,publishedCategory(id,name),address(city,state,countryName),employmentType,dateLastPublished,publicDescription,isOpen,isPublic,isDeleted,publishedZip,salary,salaryUnit`

**Comment by inflightcrewconnections** [comment]
That worked, thank you so much!
