### ISSUE TITLE
Unidentified Index Errors

### ISSUE THREAD

**Issue by Jerconjake** [bullhorn/career-portal#354]
I'm getting the following errors on when I embed the Bullhorn plugin on my wordpress site.

Notice: Undefined index: oscp_fields in /hermes/bosnacweb04/bosnacweb04ce/b1004/nf.jsquaredca/patersonham/wp-content/plugins/bullhorn-oscp/wp-oscp.php on line 793

Notice: Undefined index: oscp_job_info_chips in /hermes/bosnacweb04/bosnacweb04ce/b1004/nf.jsquaredca/patersonham/wp-content/plugins/bullhorn-oscp/wp-oscp.php on line 794

Notice: Undefined index: oscp_analytics_tracking_id in /hermes/bosnacweb04/bosnacweb04ce/b1004/nf.jsquaredca/patersonham/wp-content/plugins/bullhorn-oscp/wp-oscp.php on line 809

Notice: Undefined index: oscp_sidebar_link in /hermes/bosnacweb04/bosnacweb04ce/b1004/nf.jsquaredca/patersonham/wp-content/plugins/bullhorn-oscp/wp-oscp.php on line 815

You can see the errors here: https://www.patersonham.com/jobs/

I have reached out to the regular support and they directed me here, I have no idea how to solve this. Thanks!

**Comment by charlesabarnes** [comment]
What is in your plugin configuration?

**Comment by Jerconjake** [comment]
What do you mean? It was working correctly when I first installed it, but
now suddenly it's not.

**Comment by charlesabarnes** [comment]
Hello,

It appears as if the plugin configuration under Plugins > Career Portal may be empty.  

After review, I believe this may have been caused by the update to Wordpress 5.5.     I am doing work to mitigate this issue in the future.  

In wp-admin, you will want to update the following: 

`fields to use in API requests`: id,title,publishedCategory(id,name),address(city,state,countryName),employmentType,dateLastPublished,publicDescription,isOpen,isPublic,isDeleted,publishedZip,salary,salaryUnit

`fields to display as chips on your jobs. default is "employmentType"`:  employmentType.

I believe this should make your portal work again.   Please let me know if you have any additional questions

**Comment by Jerconjake** [comment]
Hi there!

That helped, the errors on that page are gone. But now it says An error has
occurred while loading. Please refresh the page and try again.

**Comment by charlesabarnes** [comment]
Hello,

I had to clear my cache and hard reload the page, but after that was done, it is now loading for me.

![image](https://user-images.githubusercontent.com/4327754/91770486-da6e9480-eba6-11ea-8805-c36c827ada02.png)

**Comment by Jerconjake** [comment]
Perfect, thank you so much.
