### ISSUE TITLE
Clicking submit button multiple times sends multiple web submissions

### ISSUE THREAD

**Issue by ccoffman1** [bullhorn/career-portal#36]
When a candidate goes into the career portal and gets to the stage of submitting their information.  Every click on the submit or submitting... button sends a new rest call into Bullhorn that creates a unique web response.  This is causing the jobs to be filled with duplicate web responses and the way the system handles deleting / moving web responses is based on candidate and job so they all are moved / deleted together.

## Current behavior

- Clicking the submit button multiple times sends that number of web responses in.

## Expected behavior

- One web response per candidate per job

## Steps to replicate behavior

1. Open a Job on the career portal
2. Click apply
3. Fill out information
4. Open dev tools (f12)
5. Click send / sending... buttons multiple times
- See each click sends a new payload into BH

**Comment by jgodi** [comment]
Good catch! We could implement a storage mechanism inside the browsers session storage that would show a "You have already applied to this job" message when the user tries to apply to the same job during the same browser session. 

This would keep the user from applying to the same job during the same sitting, but once they close the tab/browser and come back it will act like normal. This is because the Career Portal is anonymous to use and multiple people could share the same machine.

Would this be an acceptable solution?

**Comment by ccoffman1** [comment]
I think that'd be a great solution.

Thank you

**Comment by TheReal** [comment]
Hi @ccoffman1 , thanks for your feedback! We've introduced this feature fix per @jgodi 's spec above. The source code has been integrated back to the master branch, but hasn't been packaged for release yet. You can either pull the source code and build career-portal locally, or hang tight until the next career-portal release. Hope this helps!
