### ISSUE TITLE
Unable to add line breaks to "res" JSON files. 

### ISSUE THREAD

**Issue by bulbajackel** [bullhorn/career-portal#40]
I noticed this issue while attempting to add text to add to a field and separate it with a line break.  This issue is not critical all as I wanted to just report this behavior. 

## Current behavior

-Adding a new line (\n) or adding a line break (`<br></br> or <br/>`) does not add a line break.  It just renders what you put in.  The new line just visibly renders a line break tag(`<br>`).  

## Expected behavior

-Adding a new line and a line break breaks the line. 

## Steps to replicate behavior

1. Navigate to one of the JSON files in the en-US folder
2. For one of the variables add line break tags or add a new line. 
3. Go to the website and see what rendered.

## Screenshots

__Current__

This is an a example with a new line (\n)
![image](https://cloud.githubusercontent.com/assets/4327754/13923286/f762905a-ef4d-11e5-820f-e8315e3d8b24.png)
__Expected__
For this example I just used location but this happens with the others as well.   To make the expected behavior I just used Chrome's developer console to edit it to how I would like.
![image](https://cloud.githubusercontent.com/assets/4327754/13923297/fec1dc70-ef4d-11e5-9703-350a3d8906e3.png)

**Comment by krsween** [comment]
Hey, @bulbajackel—

The way we're repeating out the location in the DOM (shown [here](https://github.com/bullhorn/career-portal/blob/master/src/app/sidebar/sidebar.html#L31)) outputs the location as a string instead of binding to that field as HTML. 

In order to get these to render as HTML, that field could be converted into a directive that renders HTML using Angular's [html-binding functionality](https://docs.angularjs.org/api/ng/directive/ngBindHtml). I would definitely be glad to help support a feature branch that had a directive that could support strings **and** HTML if you'd like to start one. :smiley:
