### ISSUE TITLE
Run within WordPress Theme

### ISSUE THREAD

**Issue by tim41916** [bullhorn/career-portal#57]
How would I set this up to run within a WordPress Theme?

**Comment by bulbajackel** [comment]
Hello Tim, two different options that I personally like when it comes to setting it up with WordPress.  First would be creating a new page and run the career portal within a Iframe.  The next would be to link to the career portal in another directory.  If you want it to match thematically the Iframe is the best option.

**Comment by tim41916** [comment]
I am using Iframe now which is fine but I was looking to have each job show as its own post/webpage within WordPress.

**Comment by bulbajackel** [comment]
Hello Tim, 
I am sure this is possible but this is not something that is natively supported. Since the career portal has Its own URL for each job I am sure you can build a plugin for it but, it may be easier to develop a custom REST API implementation that doesn't involve the Open Source Career Portal as a backbone/frontend.

**Comment by tim41916** [comment]
Ok. Thank you for this information.
