### ISSUE TITLE
Display jobs allocated to a specific company in Bullhorn

### ISSUE THREAD

**Issue by tazplay** [bullhorn/career-portal#58]
I would like to display jobs from this page that are specific to a particular company name rather than all jobs. How would I do this? Is there a specific line I can add to my .json file?

**Comment by bulbajackel** [comment]
Hello,
It wouldn't involve an edit to the app.json file, however you will want to possibly add some custom code that adds an additional filter option except it will filter the data in a way that was not seen to the users.  Something similar was done in #46 to separate the city and state filters.

**Comment by tazplay** [comment]
Yeah, I'm completely in the dark with this - could someone point me in the right direction? Let's say javascript isn't my strength. But, I would assume it would be easy to make this type of addition as a taxonomy filter, just not sure where to start - We're presently using 'Client Company' for this filter choice in Bullhorn.

**Comment by krsween** [comment]
Hey, @tazplay—

Sorry for the delay in following up on this issue. Also, thank you for all your help in supporting this community! 

Presently our public REST interface doesn't provide the Client Corp ID for each of the job posts, so there isn't any data to create a filter of this kind. 

**Your Meta Data**
To see the full JSON for your job data with all available meta, you can add your corp id to this URL to see what's available to filter:

`https://public-rest9.bullhornstaffing.com/rest-services/[CORP_ID_HERE]/query/JobBoardPost?where=(isOpen=true)&fields=*&meta=full&count=20&orderBy=-dateLastPublished&start=0`

This will provide you with all 24 properties of the JSON that our REST API can provide.

**Building Filters**
If you'd like to build a filter for the sidebar, there are several examples of using Angular's `$filter` service inside of the `sidebar.controller.js` file. If you need more explanation about how to use Angular's `$filter` I recommend the [Angular documentation](https://docs.angularjs.org/guide/filter) or for a quick-start. [Scotch.io has a neat little tutorial on this as well](https://scotch.io/tutorials/building-custom-angularjs-filters).

Note that in order to build a filter on data that isn't presently being included by Career Portal's HTTP request (we limit the fields in the REST call to only those necessary for the app: `id,title,publishedCategory(id,name),address(city,state),employmentType,dateLastPublished,publicDescription,isOpen,isPublic,isDeleted`) you will need to modify the `search.service.js` file ~ line 18.

K.

**Comment by andriy-m** [comment]
@krsween we have a similar issue - to get a filtered job list from only one category (ie as a separate URL), is the only way to do it modifying **sidebar.controller.js** before we build/publish the Github project? Meaning there's nothing in our already-published / public-facing files we could change to achieve the same effect? I'm guessing there isn't because we don't even have an **/src/** folder in there and definitely no **sidebar.controller.js**. I've also reached out to you over email. Thanks!!

**Comment by krsween** [comment]
Hey, @andriy-m—

Thanks for reaching out. Here are some answers to your questions:

**I'd like my customers to land on a filtered jobs list.**
In order to accomplish this, you'll need to add something to the URL that Angular will interpret as a listener for a 'filter' and behave accordingly. Depending on the kind of filter you'd like to have and the complexity therein, there are a number of ways to do this. The easiest and least robust way would be to use Angular's $routeParams ([documentation](https://docs.angularjs.org/api/ngRoute/service/$routeParams)) service on the JobsList controller to listen for when there's an added query string in the URL (e.g. '?filter=location&value=California' or '?filter=category&value=Engineering').

**I'd like my users to be able to filter permanent and temporary jobs.**
First, you would need some of the job's meta data to contain a value of 'temp' or 'perm' which could be contained in the categories of the Job. You data model and particular platform's usage of the 'categories' field may force you to use a different field of the meta but that something that our Bullhorn customer success team can help you with. Once you have a field in the jobs with a value to filter on, you can modify the sidebar controller to use this filter by copying the logic from the other filters (i.e. location) and you could also use the previous solution I posed (above) to allow users to 'land' directly on a page where they're filtered.

**How do I extend this app?**
All the source files are in the 'src' directory. All controllers are written in ES6 (the latest JS version) and use Angular 1 as their framework. HTML5 and SCSS changes are pretty minimal from what you've outlined, but an understanding of those technologies may help you as you build on this platform. 

**Getting Started**
The easiest way to get up an running would be to [fork the repo](https://help.github.com/articles/fork-a-repo/) and clone that locally. From your cloned instance, create a branch (i.e. an isolated segment of modified code) for all of your new work. As you change the source code, [push that branch](https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging) up to github iteratively. I say this because when/if you have code-level questions, if you have it published online, I can help you quite easily (just @krsween in your src files on github and I'll help you as soon as I'm able). For our getting started docs, go [here](https://github.com/bullhorn/career-portal/blob/master/README.md). 

**What do I need to write code?**
The simple answer is anything that can edit text files. I use and love [Webstorm](https://www.jetbrains.com/webstorm/) and they've actually been really nice to me. [Atom](https://atom.io/) is widely used by our team and free. I really wish [VS Code](https://www.visualstudio.com/en-us/products/code-vs.aspx) would modify its ability to split panes because it is also an awesome little editor.

**Angular 1... ...huh?**
If you've never played around with Angular 1 at all, there are a ton of good resources, but a few great ones that I'd recommend. As far as books go, the [NG-Book](https://www.ng-book.com/) cannot be beat. For a great video series, [PluralSight](https://app.pluralsight.com/library/courses/angularjs-fundamentals/table-of-contents) has most of the best ones, but Youtube can also be useful.

**Comment by andriy-m** [comment]
Just to update, and for anyone trying to do something similar, we managed to get unique URLs for filtered job categories. In the end we chose **employmentType** as our filter (it was better for our use case than **category**):

1) Edited /src/app/index.route.js to add two new states/URLs, each with their own HTML template - **tempjobs** at /jobs/Temporary and **permjobs** at /jobs/Permanent : 

` $stateProvider
        .state('jobs', {
            url: '/jobs',
            templateUrl: 'app/list/list.html',
            controller: 'JobListController',
            controllerAs: 'list'
        })

        .state('tempjobs', {
            url: '/jobs/Temporary',
            templateUrl: 'app/list/list2.html',
            controller: 'JobListController',
            controllerAs: 'list'
        })

         .state('permjobs', {
            url: '/jobs/Permanent',
            templateUrl: 'app/list/list3.html',
            controller: 'JobListController',
            controllerAs: 'list'
        })`

2) Created two more copies of **/src/app/list/list.html** - at **list2.html** and **list3.html** (to be used by the new URLs as per  Step 1 above)

3) We tweaked the card-wrapper <div> in list2.html and list3.html to add a _filter:_ limiting the job list for each of those specific URLs. This may be not the most kosher way to do this in the Angular paradigm, but it works just fine in the end :) :

_<div class="cards">
        <div class="card-wrapper" data-ng-repeat="job in list.SearchService.currentListData | orderBy:dateLastPublished | **filter:{employmentType: 'Contract'}"**>_

As I mentioned, we chose employmentType as our variable/value to filter for, but just about any of the other 24 properties referenced by @krsween should do (though we did have some trouble getting the category one to work in our initial tests, mostly because we weren't 100% sure of the the proper field name in this context for "published category id", which is what we were trying to use).

**Comment by krsween** [comment]
Awesome synopsis @andriy-m! Thanks so much for contributing this to our community. Do you have a remote fork that I could take a look at and contribute to? I think I have an idea that could make this even simpler, but I'd have to look at the code to be sure.

**Comment by andriy-m** [comment]
Done. You can check out the forked repo and my minor commits for the filtering URLs here: 
https://github.com/andriy-m/career-portal
https://github.com/andriy-m/career-portal/commits/master
Only 3 files are changed
