### ISSUE TITLE
Max number of jobs displayed per category

### ISSUE THREAD

**Issue by davidjarboe** [bullhorn/career-portal#66]
INSERT SHORT DESCRIPTION EXPLAINING THE HIGH-LEVEL REASON FOR THE NEW ISSUE HERE.

## Current behavior

- If you navigate to my career portal  www.verticalrecruiting.com/careers and select "Physician - Clinical" in the left hand column / category, there are 42 open jobs that we're working.  However, only a maximum of 20 will display on the screen.

## Expected behavior

- I would expect ALL the jobs in any given category to display.

## Steps to replicate behavior

1.  Visit site,  click on filter "Physician - Clinical" and then count how many jobs are displayed on the right side of page.  (twenty will be shown.  the other 22 are not)

## Screenshots

__Current__
![max jobs displayed](https://cloud.githubusercontent.com/assets/16545518/15298879/3b03f156-1b67-11e6-9868-19478b4321ea.png)

__Expected__

**Comment by jeremy-dobler** [comment]
Hi davidjarboe,

Pagination is, in fact, a feature of career-portal as you described. If a user scrolls to the bottom of the list(20 records initially), then they will see a _Load More_ button that they can click to load more jobs. I have looked into why this isn't working on your site and it appears that the header is hiding the bottom 50px of career-portal.

By adding that element (the VR link and image) above the <section class="main overview-closed list-view"> element, it moved the list/portal down X pixels. This causes the pagination element to remain hidden and pagination to not occur as the bottom of the list has not been reached yet. 

Load More button:
![image](https://cloud.githubusercontent.com/assets/13627280/15299764/67e0df00-1b6b-11e6-85c1-35fb0a670015.png)

This can be fixed by changing the height css attribute of both elements. See picture for example
![image](https://cloud.githubusercontent.com/assets/13627280/15299493/3a85bc70-1b6a-11e6-8e88-6a3538bb79de.png)
