### ISSUE TITLE
Is there an easy way to disable the requirement for an uploaded resume?

### ISSUE THREAD

**Issue by tazplay** [bullhorn/career-portal#68]
I would like to disable the validation against requiring an uploaded resume prior to submit.

Reason being; I would like to use the career portal to capture quick contact information on a tablet during a recruitment event.

**Comment by krsween** [comment]
Hey, @tazplay—

It would be fairly easy to remove the validation logic for a resume in the `modal.controller.js`, but removing that poses a risk: our REST API needs some form of resume in order to process an application. So changing that logic could backfire if there was no LinkedIn application and no uploaded application.

I hope this helps you as you extend this app!
