### ISSUE TITLE
Iframe within wordpress

### ISSUE THREAD

**Issue by dmspitzer** [bullhorn/career-portal#81]
## Current behavior

-I am able to embed and use the portal within an iframe on a wordpress page.  The only part lacking is the Linkedin integration.  It works if i go directly to the job portal, but not in the iframe.  

page with the iframe:  http://www.scionstaffing.inkstainedcreative.com/iframe-test/

root for portal:   http://www.scionstaffing.inkstainedcreative.com/jobportal/

## Expected behavior

-I need the linkedin to work inside of the iframe

## Steps to replicate behavior

1. Attempt to apply with linkedin in the iframe:  http://www.scionstaffing.inkstainedcreative.com/iframe-test/

**Comment by bulbajackel** [comment]
I really love the color pallet you are using!

When you attempt to apply you receive the error below in dev tools

`Uncaught Error: JavaScript API Domain is restricted to www.scionstaffing.inkstainedcreative.com, www.scionstaffing.inkstainedcreative.com, www.scionstaffing.inkstainedcreative.com`

Since in your Iframe code you do not use "www."  This is what is causing the issue.   Either add  "scionstaffing.inkstainedcreative.com" To the accepted domains to the LinkedIn API  or add "www." to the iframe code.

**Comment by dmspitzer** [comment]
I'm giving this a go right now!  

Thank you for the input, it is much appreciated:)

Dave

**Comment by bulbajackel** [comment]
I just checked it out, looks like it works for you now! Let me know if you have any questions!
