### ISSUE TITLE
Need Help With Displaying Job ID

### ISSUE THREAD

**Issue by rduermyer** [bullhorn/career-portal#83]
I am working with a client using Bullhorn who has asked me to see if I can have the Job ID automatically displayed when a visitor clicks through to a specific job. After several unsuccessful attempts, support advised that the easiest work around would be to include the Job ID in the Job Title or Description. The client would prefer that the field display automatically without the need for the recruiter to remember to include it manually with every job posting. Support advised they were unable to assist and suggested I post here.

I know the Job ID is being fetched when an applicant clicks through to read the Job Description since it is displayed in the URL (/careers/#/jobs/71320) for example, but applicants aren't likely to realize that if they want to call about a specific job before applying.

It would be great if we could fetch and display the Job ID just under the heading "Job Description". Can you provide a sample code snippet and advise which files need to be updated and where?

Thank you!

**Comment by EricNLecuyer** [comment]
Hi @rduermyer!
I was able to display the job IDs with `<span>{{::job.id}}</span>` in list.html and `<span>{{::detail.job.id}}</span>` in detail.html. Let me know if it work on your end!

![capture1](https://cloud.githubusercontent.com/assets/20847607/18021647/f415d7dc-6bb6-11e6-9aac-0d0a7363b2c4.png)
![capture2](https://cloud.githubusercontent.com/assets/20847607/18021651/f7565106-6bb6-11e6-9488-806732b4e415.png)

**Comment by rduermyer** [comment]
@EricNLecuyer - Merci. I don't know if you are using the legacy or cloud version, but with the cloud version the client is using, there is no access to the list.html or detail.html files. They are called by the app.json file (presumably they live on Bullhorn's server). I looked through each of the directories installed on the client's server and the only .html file is index.html in the root. There are list.json and detail.json files in the res/ subdirectories, but they merely provide text that is to be displayed for a configuration option, not what is displayed or where. 

Detail.json, for example:

{
    "jobDescriptionHeading": "Job Description",
     "applyButton": "Apply",
    "alreadyApplied": "Already Applied",
    "sendButton": "Send",
    "iosUploadWarning": "Please view this job on our desktop site to upload a resume and apply directly. In the meantime, we'll email you a link to this job for easy access.",
    "relatedLabel": "Related",
    "viewAllJobsLabel": "View all jobs in this category",
    "jobClosedMessage": "Looks like this job has closed.",
    "jobClosedOtherJobsLabel": "You can find some similar jobs"
}

I tried adding Job Id to the list several different ways, guessing what that parameter was (looks like just :id in this version) but the display was not affected at all.

Randy

**Comment by EricNLecuyer** [comment]
Bienvenu! Your client's portal is likely already built, which will limit (or rather make very difficult) most modifications. I struggled with this too at first because, following these [instructions](https://github.com/bullhorn/career-portal/wiki/Downloading-and-Configuring), I was working with the latest release (a pre-built version) instead of the source code. To do so, you can [use the master files along with Gulp](https://github.com/bullhorn/career-portal/blob/master/README.md#building).

If you look at the [src/app](https://github.com/bullhorn/career-portal/tree/master/src/app) folder, you will see all the components of the application (header, list, sidebar, etc.) with their respective files. For example, if you want to include the job IDs in the job cards, you could go in [src/app/list/list.html](https://github.com/bullhorn/career-portal/blob/master/src/app/list/list.html) and add `<span>{{::job.id}}</span>` within `<span class="card-title-category">`.

Once your modifications are done, you can build the portal with `gulp build`. This will convert your SCSS into CSS, concatenate and minify your files, etc in a new /dist folder. The result will be similar to what you see currently on your client server.

**Comment by rduermyer** [comment]
Thanks again, Eric. Made some real progress that time but not quite home yet.

I was able to build the files with the Job ID displayed where I wanted it, but it only displays on my local PC (localhost). I cannot locate the /dist directory that was supposed to have been created during the build process,

**Comment by bulbajackel** [comment]
The dist directory should be in the main career-portal directory.   Can you post a screenshot of the directories that you are seeing?

**Comment by EricNLecuyer** [comment]
Good! I think you are almost there. The /dist folder is created only on your PC when you run `gulp build`. To make sure that it was properly created, you can run `gulp serve:dist` (that will serve your new local, optimized build). If it works, you will need to replace your client's files on their server with all the files in your local /dist folder.

Of course, handle with care and make a backup first! :-)

**Comment by rduermyer** [comment]
Success at last! Many thanks Eric!
