### ISSUE TITLE
Add New Filter or Where Condition in  Job Status = Open

### ISSUE THREAD

**Issue by developergoutam** [bullhorn/career-portal#92]
Currently there is one Condition for Job search i.e Open Jobs.
I want to add another condition Job Status = Open,
I want to display the job list where   Job Status = Open,
Please Guide me .
Not other Status 
## Current behavior

Not Checking BullHorn  Job Status,
## 
## Expected behavior

Need to Check BullHorn  Job Status where Job Status = Open
## 
## Steps to replicate behavior

1.
## Screenshots

![image](https://cloud.githubusercontent.com/assets/20899777/18343092/8526ea46-75cf-11e6-9c74-65314f058b5b.png)

**Current**

**Expected**

**Comment by charlesabarnes** [comment]
Hello, 

By default the portal looks at the Open/Closed field rather than the job status field as there could be possibly multiple statuses applicable when a job is open and accepting candidates.   We recently added a feature where you are able to access more than the standard set of fields to filter on or add fields to your job.  To enable additional fields you will need to modify your portal to add the fields into the search query, and you or an authorized support contact will need to contact Bullhorn Support to add the field as well.  

Please let me know if you have any questions.
